winzou_state_machine:
    sylius_payment:
        callbacks:
            before:
                bitbag_sylius_quadpay_plugin_refund_process:
                    on: ["refund"]
                    do: ["@bitbag_sylius_quadpay_plugin.payment_processing.refund", "process"]
                    args: ["object"]
